"""update user

Revision ID: 15e7a666a89e
Revises: b155687b0d62
Create Date: 2018-06-17 09:01:20.501802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e7a666a89e'
down_revision = 'b155687b0d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('followers_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('user', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('public_repos_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('user', sa.Column('type', sa.String(length=32), nullable=False, server_default='User'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    op.drop_column('user', 'public_repos_count')
    op.drop_column('user', 'location')
    op.drop_column('user', 'followers_count')
    # ### end Alembic commands ###
