"""add snippet

Revision ID: 39f44685b041
Revises: a1d1449974e1
Create Date: 2018-06-24 18:41:45.809000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f44685b041'
down_revision = 'a1d1449974e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('content', sa.String(length=4096), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=256), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('content_start_line', sa.Integer(), nullable=False),
    sa.Column('content_end_line', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.String(length=40), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('ratings_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snippet_topics',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('snippet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippet.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    op.add_column(u'repository', sa.Column('last_snippet_number', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'repository', 'last_snippet_number')
    op.drop_table('snippet_topics')
    op.drop_table('snippet')
    # ### end Alembic commands ###
