"""empty message

Revision ID: d440b4992c6b
Revises: 79c97523ef88
Create Date: 2018-06-17 16:28:47.856000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd440b4992c6b'
down_revision = '79c97523ef88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('followers_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('user', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('public_repos_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('user', sa.Column('type', sa.String(length=32), nullable=False, server_default='User'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    op.drop_column('user', 'public_repos_count')
    op.drop_column('user', 'location')
    op.drop_column('user', 'followers_count')
    # ### end Alembic commands ###
